version: '3.3'

# Services

services:
  xai_streamlit:
    container_name: xai_streamlit_nick
    ports:
      - '8401:8700'
      - '8402:8050'
    build: .
    volumes:
      - ./:/app/
    restart: on-failure
